import Head from "next/head";
import Image from "next/image";
import Features from "../components/Features";
import Gallery from "../components/Gallery";
import Hero from "../components/Hero";

export default function Home({ data }) {
  return (
    <div className="container mx-auto flex flex-col justify-center items-center">
      <Head>
        <title>Balaton Korut App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero data={data} />

      <Features />

      <Gallery />
    </div>
  );
}


export async function getServerSideProps() {

  const res = await fetch("https://api.openweathermap.org/data/2.5/weather?lat=46.8303&lon=17.7340&appid=8a95d3e8c0adc8a3620d2b5010bffe3c&units=metric")

  const data = await res.json();

  return {
    props: {
      data: data,
    }
  };
}
